title:           zhanglinjie博客
description:      Stay Hungry Stay Foolish
url:              # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          zhanglinjie
disqus_shortname: zhanglinjie
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         zhanglinjie博客
    url:          /
  - name:         关于
    url:          /about
  - name:         Feed
    url:          /feed.xml
  - name:         Twitter
    url:          http://twitter.com/zhanglinjie412
  - name:         Email
    url:          mailto:zhanglinjie412@gmail.com
    external:     true

highlighter:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
